import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { DbService } from '../src/db/db.service';
import { RateLimitService } from '../src/auth/rate-limit.service';
import { UserRole } from '../src/auth/current-user';
import { hashRefreshToken } from '../src/auth/tokens.service';

/**
 * Shared integration-test infrastructure.
 *
 * Credentials come from server/.env.test (gitignored; generated by
 * scripts/gen-env-test.js against a THROWAWAY scratch database). The suite
 * fails fast with instructions when the file is missing — it never falls
 * back to a development database.
 */

export interface TestEnv {
  jwtSecret: string;
  databaseUrl: string;
}

export function loadTestEnv(): TestEnv {
  const envPath = path.join(__dirname, '..', '.env.test');
  if (!fs.existsSync(envPath)) {
    throw new Error(
      'server/.env.test is missing. Integration tests run against a throwaway\n' +
        'scratch database. Create it with:\n' +
        '  1. create role/db + grant (see README "Integration tests")\n' +
        '  2. QALM_TEST_DATABASE_URL=postgres://user:pass@localhost:5432/db \\\n' +
        '       node scripts/gen-env-test.js\n' +
        '  3. DATABASE_URL=$(grep ^DATABASE_URL .env.test | cut -d= -f2-) npm run migration:run\n' +
        '  4. npm run test:e2e\n' +
        'Never point .env.test at a database you care about.',
    );
  }
  // dotenv does not override variables already present in process.env, so a
  // value exported by the caller wins over the file (escape hatch for CI).
  dotenv.config({ path: envPath });
  if (!process.env['JWT_SECRET'] || !process.env['DATABASE_URL']) {
    throw new Error('.env.test must define JWT_SECRET and DATABASE_URL');
  }
  return {
    jwtSecret: process.env['JWT_SECRET'],
    databaseUrl: process.env['DATABASE_URL'],
  };
}

export interface TestApp {
  app: INestApplication;
  db: DbService;
  /** supertest agent bound to the app's HTTP server. */
  req: ReturnType<typeof request>;
  close(): Promise<void>;
}

/** Boots the real AppModule against the scratch DB (ephemeral port). */
export async function createTestApp(): Promise<TestApp> {
  loadTestEnv();
  process.env['PORT'] = process.env['PORT'] ?? '0';

  const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
  const app = moduleRef.createNestApplication();
  await app.init();

  const db = app.get(DbService);
  // Pre-flight: migrations must be applied to the scratch DB first.
  const tables = await db.query<{ to_regclass: string | null }>(
    "SELECT to_regclass('public.users') AS to_regclass",
  );
  if (tables.rows[0]?.to_regclass === null) {
    await app.close();
    throw new Error(
      'Scratch database has no users table. Apply migrations first:\n' +
        '  DATABASE_URL=$(grep ^DATABASE_URL .env.test | cut -d= -f2-) npm run migration:run',
    );
  }

  return {
    app,
    db,
    req: request(app.getHttpServer() as Parameters<typeof request>[0]),
    async close() {
      await app.close();
    },
  };
}

/** Cleans all state between tests (order matters: FK target last). */
export async function resetDb(db: DbService): Promise<void> {
  await db.query('TRUNCATE refresh_tokens, users');
}

export function resetRateLimit(app: INestApplication): void {
  app.get(RateLimitService).reset();
}

const SHARED_FIXTURE_PASSWORD = 'fixture-Pass1';

/**
 * Inserts a user directly (bcrypt hash shared across fixtures; computed once
 * per call site that needs it). Used for roles the public API cannot create
 * (lead/tester/viewer are Admin-created in the 2b2 card).
 */
export async function seedUser(
  db: DbService,
  bcrypt: { hashSync(plain: string, cost: number): string },
  params: {
    email: string;
    name?: string;
    role: UserRole;
    isActive?: boolean;
    mustChangePassword?: boolean;
  },
): Promise<{ id: string; password: string }> {
  const result = await db.query<{ id: string }>(
    `INSERT INTO users (email, name, role, password_hash, is_active, must_change_password)
     VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`,
    [
      params.email,
      params.name ?? 'Fixture User',
      params.role,
      bcrypt.hashSync(SHARED_FIXTURE_PASSWORD, 12),
      params.isActive ?? true,
      params.mustChangePassword ?? false,
    ],
  );
  const row = result.rows[0];
  if (!row) throw new Error('seedUser insert failed');
  return { id: row.id, password: SHARED_FIXTURE_PASSWORD };
}

/** Test-only refresh-token persistence (mirrors RefreshTokenStore). */
export async function insertRefreshToken(
  db: DbService,
  userId: string,
  raw: string,
  ttlSeconds: number,
): Promise<void> {
  await db.query(
    `INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
     VALUES ($1, $2, now() + make_interval(secs => $3))`,
    [hashRefreshToken(raw), userId, ttlSeconds],
  );
}

/** Extracts the qalm_refresh cookie value from a supertest response. */
export function refreshCookieOf(response: request.Response): string | undefined {
  const cookies = response.headers['set-cookie'];
  if (!Array.isArray(cookies)) return undefined;
  for (const cookie of cookies as string[]) {
    if (cookie.startsWith('qalm_refresh=')) {
      return cookie.slice('qalm_refresh='.length).split(';')[0] || undefined;
    }
  }
  return undefined;
}

/** All Set-Cookie headers (raw) whose key is qalm_refresh. */
export function refreshCookieHeaders(response: request.Response): string[] {
  const cookies = response.headers['set-cookie'];
  if (!Array.isArray(cookies)) return [];
  return (cookies as string[]).filter((c) => c.startsWith('qalm_refresh='));
}

export { SHARED_FIXTURE_PASSWORD };
